import { addDays, todayISO } from "./dates";
import type { LedgerState } from "./types";

export function defaultCategories(): LedgerState["categories"] {
  return [
    { id: "food", name: "Food", kind: "expense" },
    { id: "travel", name: "Travel", kind: "expense" },
    { id: "home", name: "Home", kind: "expense" },
    { id: "health", name: "Health", kind: "expense" },
    { id: "fun", name: "Fun", kind: "expense" },
    { id: "bills", name: "Bills", kind: "expense" },
    { id: "other", name: "Other", kind: "expense" },
    { id: "salary", name: "Salary", kind: "income" },
    { id: "freelance", name: "Freelance", kind: "income" },
  ];
}

export function createSeedState(): LedgerState {
  const t = todayISO();
  return {
    settings: { currency: "INR", theme: "system", startOfMonth: 1 },
    accounts: [
      { id: "cash", name: "Wallet", kind: "cash", openingBalance: 4200 },
      { id: "card", name: "Everyday card", kind: "card", openingBalance: 0 },
      { id: "bank", name: "Savings", kind: "bank", openingBalance: 86000 },
    ],
    categories: defaultCategories(),
    budgets: [
      { id: "b-food", categoryId: "food", monthlyLimit: 12000 },
      { id: "b-travel", categoryId: "travel", monthlyLimit: 4000 },
      { id: "b-fun", categoryId: "fun", monthlyLimit: 3000 },
      { id: "b-bills", categoryId: "bills", monthlyLimit: 8000 },
    ],
    transactions: [
      {
        id: "seed-inc-1",
        amount: 72000,
        type: "income",
        categoryId: "salary",
        accountId: "bank",
        toAccountId: null,
        date: addDays(t, -12),
        note: "Monthly pay",
        merchant: "Employer",
      },
      {
        id: "seed-1",
        amount: 486,
        type: "expense",
        categoryId: "food",
        accountId: "card",
        toAccountId: null,
        date: addDays(t, -1),
        note: "Lunch",
        merchant: "Cafe Maple",
      },
      {
        id: "seed-2",
        amount: 1299,
        type: "expense",
        categoryId: "food",
        accountId: "card",
        toAccountId: null,
        date: addDays(t, -2),
        note: "Groceries",
        merchant: "Green Mart",
      },
      {
        id: "seed-3",
        amount: 210,
        type: "expense",
        categoryId: "travel",
        accountId: "cash",
        toAccountId: null,
        date: addDays(t, -3),
        note: "Metro",
        merchant: "Transit",
      },
      {
        id: "seed-4",
        amount: 1899,
        type: "expense",
        categoryId: "fun",
        accountId: "card",
        toAccountId: null,
        date: addDays(t, -5),
        note: "Cinema",
        merchant: "Plex",
      },
      {
        id: "seed-5",
        amount: 6400,
        type: "expense",
        categoryId: "bills",
        accountId: "bank",
        toAccountId: null,
        date: addDays(t, -8),
        note: "Electricity + wifi",
        merchant: "Utilities",
      },
      {
        id: "seed-6",
        amount: 850,
        type: "expense",
        categoryId: "health",
        accountId: "card",
        toAccountId: null,
        date: addDays(t, -9),
        note: "Pharmacy",
        merchant: "Well & Co",
      },
      {
        id: "seed-7",
        amount: 2400,
        type: "expense",
        categoryId: "home",
        accountId: "bank",
        toAccountId: null,
        date: addDays(t, -10),
        note: "Housewares",
        merchant: "Habitat",
      },
      {
        id: "seed-8",
        amount: 320,
        type: "expense",
        categoryId: "food",
        accountId: "cash",
        toAccountId: null,
        date: addDays(t, -6),
        note: "Coffee",
        merchant: "Roast",
      },
      {
        id: "seed-9",
        amount: 1500,
        type: "income",
        categoryId: "freelance",
        accountId: "bank",
        toAccountId: null,
        date: addDays(t, -4),
        note: "Weekend gig",
        merchant: "Client",
      },
      {
        id: "seed-tr",
        amount: 3000,
        type: "transfer",
        categoryId: null,
        accountId: "bank",
        toAccountId: "cash",
        date: addDays(t, -7),
        note: "ATM",
        merchant: "",
      },
    ],
  };
}
